# Generated by Django 4.2.17 on 2024-12-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_book_goodmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_GoodModel',
        ),
    ]
